version: "3"

services:
  #MongoDB
  mongo_db:
    container_name: database_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  app:
    build: .
    ports:
      - 4000:3001
    environment:
      APP_NAME: LearnDocker
      PORT: 3001
      MONGO_URI: mongodb+srv://1234:1234@cluster0.ovqbyle.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}