version: "3"

services:
  # MongoDB
  mongo_db:
    container_name: database_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  app:
    build: .
    ports:
      - 4000:3001
    environment:
      PORT: ${PORT}
      MONGO_URI: ${MONGO_URI}
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
